services:
  backend:
    build:
      context: ./backend
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - FLASK_APP=app.py
      - FLASK_ENV=development

  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:80'
    environment:
      - REACT_APP_API_URL=http://backend:5000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
